services:
  # Backend API Service
  - type: web
    name: itinerary-server
    env: node
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: VITE_FRONTEND_URL
        value: https://itinerary-paoj.onrender.com

  # Frontend Static Site
  - type: web
    name: itinerary-paoj
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_BACK_END_URL
        value: https://itinerary-server.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 